server:
  port: 10086
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8860/eureka

zuul:
  routes:
    userservice:     #id  （自己取的）
      path: /user/**
      serviceId: userservice
      strip-prefix: true    #是否去除前缀
  ignored-services:   # 忽略的服务




