server:
  port: 8856
spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8860/eureka
   # registry-fetch-interval-seconds: 10   #拉取服务列表的周期
    #fetch-registry: true  #是否拉取服务列表
userservice:
  ribbon:
    NFloadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
ribbon:
  ConnectionTimeOut: 500  #如果500毫秒内未连接则抛出异常
  ReadTimeOuot: 2000   #r如果已连接但是2000毫秒内没有返回数据则抛出异常

hystrix:
  command:
    #default: #针对全局
    #  execution:
   #     isolation:
  #        thread:
 #           timeoutInMilliseconds: 2500
    userservice:  #针对userservice微服务
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1500   如果1500毫秒内没有连接上熔断器则断开
